export const actions = {
    ADD_CATEGORY: 'ADD_CATEGORY',
    REMOVE_CATEGORY: 'REMOVE_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
};

export const error = {
    REMOVING_DEFAULT_CATEGORY: 'REMOVING_DEFAULT_CATEGORY'
};