export const transactionType = {
    INCOME: 'INCOME',
    EXPENSE: 'EXPENSE',
};

export const actions = {
    ADD_TRANSACTION: 'ADD_TRANSACTION',
    REMOVE_TRANSACTION: 'REMOVE_TRANSACTION',
    UPDATE_TRANSACTION: 'UPDATE_TRANSACTION'
};