export const transactionType = {
    INCOME: 'INCOME',
    EXPENSE: 'EXPENSE',
};

export const actions = {
    ADD_TRANSACTION: 'ADD_TRANSACTION',
    REMOVE_TRANSACTION: 'REMOVE_TRANSACTION',
    REMOVE_TRANSACTION_BY_ACCOUNT_NAME: 'REMOVE_TRANSACTION_BY_ACCOUNT_NAME',
};